import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import type Database from "better-sqlite3";
import type { Storage } from "../../storage/src/index.js";
import type { ModelPolicy as CoreModelPolicy } from "../../contracts/src/index.js";

/**
 * Durable, read-mostly production planning.  This package never creates, runs,
 * retries, or mutates Flow jobs; the job engine remains the only effect owner.
 */
export type WorkspaceStorage = Pick<Storage, "db"> | { db: Database.Database };
export type ReferenceRole = "identity" | "start_frame" | "end_frame";
export type RunState = "RUNNABLE" | "BLOCKED" | "STALE" | "UNSUPPORTED";
/** Mirrors model-policy v1. Capability is explicit evidence, never inferred from a model label. */
export type ModelPolicy = CoreModelPolicy & { capabilityState: "supported" | "unsupported" | "unknown"; unsupportedReason?: string; evidenceDate?: string };
export type ReferenceSource = { kind: "local" | "provider" | "generated"; locator?: string; providerMediaId?: string; providerProjectId?: string; jobId?: string; receiptSha256?: string };
export type GenerationCandidate = { id: string; sceneId: string; revisionId: string; jobId: string; requestHash: string; budgetLedgerId: string; budgetStepKey: string; modelPolicy: ModelPolicy; jobEvidence: { assetHashes: Array<{providerAssetRef:string;sha256:string|null}>; receiptHashes: string[] }; state: RunState; blockers: string[]; nextSafeOperation: string };

const hash = (value: string | Buffer) => createHash("sha256").update(value).digest("hex");
const stableId = (prefix: string, value: string) => `${prefix}_${hash(value).slice(0, 20)}`;
const now = () => new Date().toISOString();

export class ProductionWorkspace {
  readonly db: Database.Database;
  constructor(storage: WorkspaceStorage) { this.db = storage.db; this.migrate(); }

  private migrate() {
    this.db.exec(`
      CREATE TABLE IF NOT EXISTS pw_projects (id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS pw_entities (id TEXT PRIMARY KEY, project_id TEXT NOT NULL, display_name TEXT NOT NULL, kind TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(project_id, display_name), FOREIGN KEY(project_id) REFERENCES pw_projects(id));
      CREATE TABLE IF NOT EXISTS pw_reference_versions (id TEXT PRIMARY KEY, entity_id TEXT NOT NULL, ordinal INTEGER NOT NULL, sha256 TEXT NOT NULL CHECK(length(sha256)=64), role TEXT NOT NULL CHECK(role IN ('identity','start_frame','end_frame')), source_json TEXT NOT NULL, created_at TEXT NOT NULL, superseded_at TEXT, UNIQUE(entity_id, ordinal), UNIQUE(entity_id, sha256, role), FOREIGN KEY(entity_id) REFERENCES pw_entities(id));
      CREATE TABLE IF NOT EXISTS pw_scenes (id TEXT PRIMARY KEY, project_id TEXT NOT NULL, ordinal INTEGER NOT NULL, current_revision_id TEXT, created_at TEXT NOT NULL, UNIQUE(project_id, ordinal), FOREIGN KEY(project_id) REFERENCES pw_projects(id));
      CREATE TABLE IF NOT EXISTS pw_scene_revisions (id TEXT PRIMARY KEY, scene_id TEXT NOT NULL, ordinal INTEGER NOT NULL, prompt TEXT NOT NULL, model_policy_json TEXT NOT NULL, invalidated_at TEXT, invalidation_reason TEXT, created_at TEXT NOT NULL, UNIQUE(scene_id, ordinal), FOREIGN KEY(scene_id) REFERENCES pw_scenes(id));
      CREATE TABLE IF NOT EXISTS pw_revision_references (revision_id TEXT NOT NULL, reference_version_id TEXT NOT NULL, position INTEGER NOT NULL, PRIMARY KEY(revision_id, reference_version_id), UNIQUE(revision_id, position), FOREIGN KEY(revision_id) REFERENCES pw_scene_revisions(id), FOREIGN KEY(reference_version_id) REFERENCES pw_reference_versions(id));
      CREATE TABLE IF NOT EXISTS pw_scene_dependencies (scene_id TEXT NOT NULL, depends_on_scene_id TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY(scene_id,depends_on_scene_id), CHECK(scene_id<>depends_on_scene_id), FOREIGN KEY(scene_id) REFERENCES pw_scenes(id), FOREIGN KEY(depends_on_scene_id) REFERENCES pw_scenes(id));
      CREATE TABLE IF NOT EXISTS pw_generation_candidates (id TEXT PRIMARY KEY, scene_id TEXT NOT NULL, revision_id TEXT NOT NULL, job_id TEXT NOT NULL UNIQUE, request_hash TEXT NOT NULL, budget_ledger_id TEXT NOT NULL, budget_step_key TEXT NOT NULL, model_policy_json TEXT NOT NULL, created_at TEXT NOT NULL, invalidated_at TEXT, invalidation_reason TEXT, UNIQUE(scene_id,revision_id,job_id), FOREIGN KEY(scene_id) REFERENCES pw_scenes(id), FOREIGN KEY(revision_id) REFERENCES pw_scene_revisions(id));
      CREATE TABLE IF NOT EXISTS pw_candidate_job_evidence (candidate_id TEXT PRIMARY KEY, asset_hashes_json TEXT NOT NULL, receipt_hashes_json TEXT NOT NULL, captured_at TEXT NOT NULL, FOREIGN KEY(candidate_id) REFERENCES pw_generation_candidates(id));
    `);
  }

  createProject(input: { id?: string; name: string }) { const id=input.id ?? stableId("project",input.name); this.db.prepare("INSERT OR IGNORE INTO pw_projects(id,name,created_at) VALUES(?,?,?)").run(id,input.name,now()); return this.project(id); }
  createEntity(input: { id?: string; projectId: string; displayName: string; kind?: string }) { this.mustProject(input.projectId); const id=input.id ?? stableId("entity",`${input.projectId}:${input.displayName}`); this.db.prepare("INSERT OR IGNORE INTO pw_entities(id,project_id,display_name,kind,created_at) VALUES(?,?,?,?,?)").run(id,input.projectId,input.displayName,input.kind??"character",now()); return this.entity(id); }
  addReferenceVersion(input: { entityId: string; sha256: string; source: ReferenceSource; role: ReferenceRole }) {
    this.mustEntity(input.entityId); if(!/^[a-f0-9]{64}$/.test(input.sha256)) throw new Error("REFERENCE_HASH_REQUIRED"); this.verifyReferenceSource(input.source,input.sha256);
    const old=this.db.prepare("SELECT * FROM pw_reference_versions WHERE entity_id=? AND sha256=? AND role=?").get(input.entityId,input.sha256,input.role) as RefRow|undefined; if(old) return ref(old);
    const ordinal=(this.db.prepare("SELECT COALESCE(MAX(ordinal),0)+1 n FROM pw_reference_versions WHERE entity_id=?").get(input.entityId) as {n:number}).n;
    const id=stableId("ref",`${input.entityId}:${ordinal}:${input.sha256}:${input.role}`), created=now();
    this.db.transaction(()=>{ this.db.prepare("UPDATE pw_reference_versions SET superseded_at=? WHERE entity_id=? AND role=? AND superseded_at IS NULL").run(created,input.entityId,input.role); this.db.prepare("INSERT INTO pw_reference_versions(id,entity_id,ordinal,sha256,role,source_json,created_at) VALUES(?,?,?,?,?,?,?)").run(id,input.entityId,ordinal,input.sha256,input.role,JSON.stringify(input.source),created); this.invalidateRevisionsUsingEntity(input.entityId,"reference version replaced"); })();
    return this.reference(id);
  }
  createScenePlan(input: { projectId: string; sceneId?: string; ordinal: number; prompt: string; modelPolicy: ModelPolicy; referenceVersionIds: string[] }) {
    this.mustProject(input.projectId); this.assertRefs(input.referenceVersionIds,input.projectId); const id=input.sceneId ?? stableId("scene",`${input.projectId}:${input.ordinal}`); const created=now();
    this.db.transaction(()=>{this.db.prepare("INSERT INTO pw_scenes(id,project_id,ordinal,created_at) VALUES(?,?,?,?)").run(id,input.projectId,input.ordinal,created);this.insertRevision(id,input.prompt,input.modelPolicy,input.referenceVersionIds,created);})(); return this.scene(id);
  }
  reviseScene(input: { sceneId: string; prompt?: string; modelPolicy?: ModelPolicy; referenceVersionIds?: string[] }) {
    const current=this.currentRevision(input.sceneId),scene=this.scene(input.sceneId); const refs=input.referenceVersionIds ?? this.referenceIds(current.id); this.assertRefs(refs,scene.projectId); const created=now();
    this.db.transaction(()=>{this.db.prepare("UPDATE pw_scene_revisions SET invalidated_at=?, invalidation_reason=? WHERE id=?").run(created,"superseded by edit",current.id);this.invalidateCandidatesForRevision(current.id,"scene revised");this.insertRevision(input.sceneId,input.prompt??current.prompt,input.modelPolicy??current.modelPolicy,refs,created);this.invalidateDescendants(input.sceneId,"upstream scene revised");})(); return this.scene(input.sceneId);
  }
  addDependency(input: { sceneId: string; dependsOnSceneId: string }) { const a=this.scene(input.sceneId),b=this.scene(input.dependsOnSceneId); if(a.projectId!==b.projectId) throw new Error("CROSS_PROJECT_DEPENDENCY"); this.db.transaction(()=>{this.db.prepare("INSERT OR IGNORE INTO pw_scene_dependencies(scene_id,depends_on_scene_id,created_at) VALUES(?,?,?)").run(input.sceneId,input.dependsOnSceneId,now());if(this.hasPath(input.dependsOnSceneId,input.sceneId)) {this.db.prepare("DELETE FROM pw_scene_dependencies WHERE scene_id=? AND depends_on_scene_id=?").run(input.sceneId,input.dependsOnSceneId);throw new Error("DEPENDENCY_CYCLE");}})(); return this.scene(input.sceneId); }
  planGenerationCandidate(input: { sceneId: string; revisionId?: string; jobId: string; requestHash: string; budgetLedgerId: string; budgetStepKey: string; modelPolicy?: ModelPolicy }) {
    const revision=input.revisionId ? this.revision(input.revisionId) : this.currentRevision(input.sceneId); if(revision.sceneId!==input.sceneId) throw new Error("REVISION_SCENE_MISMATCH"); if(!/^[a-f0-9]{64}$/.test(input.requestHash)) throw new Error("REQUEST_HASH_REQUIRED");
    this.assertExistingJobBinding(input.jobId,input.requestHash,input.budgetLedgerId,input.budgetStepKey); this.verifyRevisionReferences(revision.id);
    const policy=input.modelPolicy??revision.modelPolicy, id=stableId("candidate",`${input.sceneId}:${revision.id}:${input.jobId}`); this.db.transaction(()=>{this.db.prepare("INSERT OR IGNORE INTO pw_generation_candidates(id,scene_id,revision_id,job_id,request_hash,budget_ledger_id,budget_step_key,model_policy_json,created_at) VALUES(?,?,?,?,?,?,?,?,?)").run(id,input.sceneId,revision.id,input.jobId,input.requestHash,input.budgetLedgerId,input.budgetStepKey,JSON.stringify(policy),now());this.db.prepare("INSERT OR IGNORE INTO pw_candidate_job_evidence(candidate_id,asset_hashes_json,receipt_hashes_json,captured_at) VALUES(?,?,?,?)").run(id,JSON.stringify(this.snapshotJobEvidence(input.jobId).assetHashes),JSON.stringify(this.snapshotJobEvidence(input.jobId).receiptHashes),now());})(); return this.candidate(id);
  }
  /** Alias for app/engine adapters: validates an already-created immutable job binding only. */
  bindExistingJob(input: { sceneId: string; revisionId?: string; jobId: string; requestHash: string; budgetLedgerId: string; budgetStepKey: string; modelPolicy?: ModelPolicy }) { return this.planGenerationCandidate(input); }
  /** Builds a side-effect-free external request. flowctl must pass it to engine.create(...), then bind that returned job. */
  buildExternalRequest(input:{sceneId:string;revisionId?:string;idempotencyKey:string;project:{name:string;reuse?:boolean};mode:"text_to_video"|"extend_video"|"first_frame_to_video"|"first_last_frames_to_video"|"ingredients_to_video"|"edit_video";sourceVideo?:{path:string;name?:string};aspectRatio:"16:9"|"9:16";durationSeconds:number;resolution:string;outputs:number;budgetLedgerId:string;budgetStepKey:string}){
    const revision=input.revisionId?this.revision(input.revisionId):this.currentRevision(input.sceneId);if(revision.sceneId!==input.sceneId)throw new Error("REVISION_SCENE_MISMATCH");this.verifyRevisionReferences(revision.id);const refs=this.referenceIds(revision.id).map(id=>this.reference(id));const local=refs.filter(r=>r.source.kind==="local").map(r=>({path:r.source.locator!,name:r.id}));
    if(input.mode==="edit_video"){if(revision.modelPolicy.requiredFamily!=="gemini_omni_flash_1_1")throw new Error("EDIT_POLICY_REQUIRES_OMNI");if(!input.sourceVideo)throw new Error("EDIT_SOURCE_VIDEO_REQUIRED");let bytes:Buffer;try{bytes=readFileSync(input.sourceVideo.path);}catch{throw new Error("EDIT_SOURCE_VIDEO_MISSING");}return {backend:"flow_ui" as const,idempotency_key:input.idempotencyKey,project:input.project,mode:input.mode,prompt:revision.prompt,prompt_mode:"verbatim" as const,model_policy:{version:revision.modelPolicy.version,required_family:revision.modelPolicy.requiredFamily,api_code:revision.modelPolicy.apiCode,allow_fallback:false as const,execution_backend:"flow_ui" as const,selection_source:revision.modelPolicy.selectionSource},aspect_ratio:input.aspectRatio,duration_seconds:input.durationSeconds,resolution:input.resolution,outputs:input.outputs,inputs:{source_video:{path:input.sourceVideo.path,name:input.sourceVideo.name,content_sha256:hash(bytes)}},cost_policy:{max_credits:200 as const,confirm_above:200 as const,reject_when_unknown:true as const},budget_group:{ledger_id:input.budgetLedgerId,step_key:input.budgetStepKey},workspace:{scene_id:input.sceneId,revision_id:revision.id,reference_version_ids:refs.map(r=>r.id),capability_state:revision.modelPolicy.capabilityState,flow_ui_edit_unverified:true}};
    }if(input.mode!=="text_to_video"&&!local.length)throw new Error("GENERATION_INPUT_REFERENCE_REQUIRED");
    return {backend:"flow_ui" as const,idempotency_key:input.idempotencyKey,project:input.project,mode:input.mode,prompt:revision.prompt,prompt_mode:"verbatim" as const,model_policy:{version:revision.modelPolicy.version,required_family:revision.modelPolicy.requiredFamily,api_code:revision.modelPolicy.apiCode,allow_fallback:false as const,execution_backend:"flow_ui" as const,selection_source:revision.modelPolicy.selectionSource},aspect_ratio:input.aspectRatio,duration_seconds:input.durationSeconds,resolution:input.resolution,outputs:input.outputs,inputs:input.mode==="text_to_video"?undefined:{ingredients:local},cost_policy:{max_credits:200 as const,confirm_above:200 as const,reject_when_unknown:true as const},budget_group:{ledger_id:input.budgetLedgerId,step_key:input.budgetStepKey},workspace:{scene_id:input.sceneId,revision_id:revision.id,reference_version_ids:refs.map(r=>r.id),capability_state:revision.modelPolicy.capabilityState}};
  }
  candidate(id: string): GenerationCandidate { const row=this.db.prepare("SELECT * FROM pw_generation_candidates WHERE id=?").get(id) as CandidateRow|undefined;if(!row)throw new Error("CANDIDATE_NOT_FOUND"); const status=this.sceneStatus(row.scene_id); const policy=JSON.parse(row.model_policy_json) as ModelPolicy,evidence=this.db.prepare("SELECT * FROM pw_candidate_job_evidence WHERE candidate_id=?").get(id) as CandidateEvidenceRow|undefined; if(!evidence)throw new Error("CANDIDATE_EVIDENCE_MISSING"); const blockers=[...status.blockers,...this.jobExecutionBlockers(row.job_id)]; if(row.invalidated_at) blockers.push(`candidate invalidated: ${row.invalidation_reason}`); const state:RunState=row.invalidated_at?"STALE":policy.capabilityState==="unsupported"?"UNSUPPORTED":blockers.length?"BLOCKED":"RUNNABLE"; return {id:row.id,sceneId:row.scene_id,revisionId:row.revision_id,jobId:row.job_id,requestHash:row.request_hash,budgetLedgerId:row.budget_ledger_id,budgetStepKey:row.budget_step_key,modelPolicy:policy,jobEvidence:{assetHashes:JSON.parse(evidence.asset_hashes_json),receiptHashes:JSON.parse(evidence.receipt_hashes_json)},state,blockers,nextSafeOperation:state==="RUNNABLE"?"Prepare this immutable existing job through JobEngine; it alone may reserve the shared ledger and issue a browser ticket.":state==="UNSUPPORTED"?"Observe a supported current Flow UI capability before creating a job.":state==="STALE"?"Create a new scene revision and new candidate; retain this job and receipt for audit.":"Resolve listed dependencies or use reconciliation for an already submitted job."}; }
  sceneStatus(sceneId: string) { const scene=this.scene(sceneId), revision=this.currentRevision(sceneId); const blockers:string[]=[]; if(revision.invalidatedAt) blockers.push("current revision is invalidated"); for(const dep of this.dependencies(sceneId)){const d=this.sceneStatusShallow(dep);if(d.currentRevisionInvalidated)blockers.push(`dependency ${dep} has no current valid revision`);if(!d.hasTerminalAsset)blockers.push(`dependency ${dep} has no terminal generated asset for its current revision`);} if(revision.modelPolicy.capabilityState!=="supported")blockers.push(revision.modelPolicy.unsupportedReason??"current Flow UI capability evidence is missing or unsupported"); return {sceneId,projectId:scene.projectId,revisionId:revision.id,blockers,state:revision.modelPolicy.capabilityState==="unsupported"?"UNSUPPORTED" as RunState:blockers.length?"BLOCKED" as RunState:"RUNNABLE" as RunState}; }
  dashboardSnapshot(projectId: string) { this.mustProject(projectId); const scenes=this.db.prepare("SELECT id FROM pw_scenes WHERE project_id=? ORDER BY ordinal").all(projectId) as Array<{id:string}>; return {project:this.project(projectId),entities:this.db.prepare("SELECT id FROM pw_entities WHERE project_id=? ORDER BY display_name").all(projectId).map((x:any)=>this.entity(x.id)),scenes:scenes.map(x=>({scene:this.scene(x.id),status:this.sceneStatus(x.id),candidates:(this.db.prepare("SELECT id FROM pw_generation_candidates WHERE scene_id=? ORDER BY created_at").all(x.id) as Array<{id:string}>).map(c=>this.candidate(c.id))}))}; }
  listProjects(){return (this.db.prepare("SELECT * FROM pw_projects ORDER BY created_at").all() as ProjectRow[]).map(project);}
  listScenes(projectId:string){this.mustProject(projectId);return (this.db.prepare("SELECT id FROM pw_scenes WHERE project_id=? ORDER BY ordinal").all(projectId) as Array<{id:string}>).map(x=>this.scene(x.id));}

  private insertRevision(sceneId:string,prompt:string,modelPolicy:ModelPolicy,refs:string[],created:string){const ordinal=(this.db.prepare("SELECT COALESCE(MAX(ordinal),0)+1 n FROM pw_scene_revisions WHERE scene_id=?").get(sceneId) as {n:number}).n,id=stableId("revision",`${sceneId}:${ordinal}:${hash(prompt)}:${hash(JSON.stringify(modelPolicy))}`);this.db.prepare("INSERT INTO pw_scene_revisions(id,scene_id,ordinal,prompt,model_policy_json,created_at) VALUES(?,?,?,?,?,?)").run(id,sceneId,ordinal,prompt,JSON.stringify(modelPolicy),created);const q=this.db.prepare("INSERT INTO pw_revision_references(revision_id,reference_version_id,position) VALUES(?,?,?)");refs.forEach((refId,i)=>q.run(id,refId,i));this.db.prepare("UPDATE pw_scenes SET current_revision_id=? WHERE id=?").run(id,sceneId);}
  private invalidateRevisionsUsingEntity(entityId:string,reason:string){const rows=this.db.prepare("SELECT DISTINCT rr.revision_id FROM pw_revision_references rr JOIN pw_reference_versions rv ON rv.id=rr.reference_version_id WHERE rv.entity_id=?").all(entityId) as Array<{revision_id:string}>;for(const r of rows){this.db.prepare("UPDATE pw_scene_revisions SET invalidated_at=?, invalidation_reason=? WHERE id=? AND invalidated_at IS NULL").run(now(),reason,r.revision_id);const scene=this.revision(r.revision_id).sceneId;this.invalidateCandidatesForRevision(r.revision_id,reason);this.invalidateDescendants(scene,reason);}}
  private invalidateDescendants(sceneId:string,reason:string){const rows=this.db.prepare("WITH RECURSIVE d(id) AS (SELECT scene_id FROM pw_scene_dependencies WHERE depends_on_scene_id=? UNION SELECT x.scene_id FROM pw_scene_dependencies x JOIN d ON x.depends_on_scene_id=d.id) SELECT id FROM d").all(sceneId) as Array<{id:string}>;for(const x of rows){const rev=this.currentRevision(x.id);this.db.prepare("UPDATE pw_scene_revisions SET invalidated_at=?, invalidation_reason=? WHERE id=? AND invalidated_at IS NULL").run(now(),reason,rev.id);this.invalidateCandidatesForRevision(rev.id,reason);}}
  private invalidateCandidatesForRevision(revisionId:string,reason:string){this.db.prepare("UPDATE pw_generation_candidates SET invalidated_at=?, invalidation_reason=? WHERE revision_id=? AND invalidated_at IS NULL").run(now(),reason,revisionId);}
  private hasPath(start:string,target:string){return Boolean(this.db.prepare("WITH RECURSIVE p(id) AS (SELECT depends_on_scene_id FROM pw_scene_dependencies WHERE scene_id=? UNION SELECT d.depends_on_scene_id FROM pw_scene_dependencies d JOIN p ON d.scene_id=p.id) SELECT 1 FROM p WHERE id=? LIMIT 1").get(start,target));}
  private dependencies(sceneId:string){return (this.db.prepare("SELECT depends_on_scene_id id FROM pw_scene_dependencies WHERE scene_id=?").all(sceneId) as Array<{id:string}>).map(x=>x.id);}
  private sceneStatusShallow(id:string){const rev=this.currentRevision(id),terminal=Boolean(this.db.prepare("SELECT 1 FROM pw_generation_candidates c JOIN jobs j ON j.id=c.job_id JOIN assets a ON a.job_id=j.id WHERE c.scene_id=? AND c.revision_id=? AND c.invalidated_at IS NULL AND j.state IN ('GENERATED','COMPLETED','PARTIALLY_COMPLETED') AND a.sha256 IS NOT NULL LIMIT 1").get(id,rev.id));return {currentRevisionInvalidated:Boolean(rev.invalidatedAt),hasTerminalAsset:terminal};}
  private jobExecutionBlockers(jobId:string){const job=this.db.prepare("SELECT state FROM jobs WHERE id=?").get(jobId) as {state:string}|undefined;if(!job)return ["bound job is missing"];if(["GENERATED","COMPLETED","PARTIALLY_COMPLETED","FAILED","CANCELLED_PRE_SUBMIT","SUBMISSION_UNCERTAIN","RESULT_AMBIGUOUS"].includes(job.state))return [`bound job is ${job.state}; no automatic execution is allowed`];if(this.db.prepare("SELECT 1 FROM submission_attempts WHERE job_id=? LIMIT 1").get(jobId))return ["bound job already has immutable submission intent; reconciliation only"];return [];}
  private assertExistingJobBinding(jobId:string,requestHash:string,ledgerId:string,stepKey:string){const job=this.db.prepare("SELECT request_hash,request_json FROM jobs WHERE id=?").get(jobId) as {request_hash:string;request_json:string}|undefined;if(!job||job.request_hash!==requestHash)throw new Error("EXISTING_JOB_HASH_MISMATCH");let request:any;try{request=JSON.parse(job.request_json);}catch{throw new Error("EXISTING_JOB_REQUEST_INVALID");}if(request.budgetContext?.ledgerId!==ledgerId||request.budgetContext?.stepKey!==stepKey)throw new Error("EXISTING_JOB_BUDGET_BINDING_MISMATCH");this.verifyFrozenJobInputs(request);const step=this.db.prepare("SELECT job_id,request_hash FROM budget_steps WHERE parent_id=? AND step_key=?").get(ledgerId,stepKey) as {job_id:string|null;request_hash:string|null}|undefined;if(step&&(step.job_id!==jobId||step.request_hash!==requestHash))throw new Error("EXISTING_BUDGET_STEP_MISMATCH");if(!step&&this.db.prepare("SELECT 1 FROM submission_attempts WHERE job_id=? LIMIT 1").get(jobId))throw new Error("SUBMITTED_JOB_BUDGET_STEP_MISSING");}
  private verifyFrozenJobInputs(request:any){const inputs=[request.inputs?.firstFrame,request.inputs?.lastFrame,...(request.inputs?.ingredients??[])].filter(Boolean);for(const input of inputs){if(!input.path||!input.contentSha256)throw new Error("JOB_INPUT_HASH_MISSING");let bytes:Buffer;try{bytes=readFileSync(input.path);}catch{throw new Error("JOB_INPUT_MISSING");}if(hash(bytes)!==input.contentSha256)throw new Error("JOB_INPUT_HASH_MISMATCH");}}
  private verifyReferenceSource(source:ReferenceSource,sha256:string){if(source.kind!=="local")return;if(!source.locator)throw new Error("REFERENCE_LOCAL_LOCATOR_REQUIRED");let bytes:Buffer;try{bytes=readFileSync(source.locator);}catch{throw new Error("REFERENCE_MATERIAL_MISSING");}if(hash(bytes)!==sha256)throw new Error("REFERENCE_HASH_MISMATCH");}
  private verifyRevisionReferences(revisionId:string){for(const id of this.referenceIds(revisionId)){const r=this.reference(id);this.verifyReferenceSource(r.source,r.sha256);}}
  private snapshotJobEvidence(jobId:string){const assets=(this.db.prepare("SELECT provider_asset_ref,sha256 FROM assets WHERE job_id=? ORDER BY provider_asset_ref").all(jobId) as Array<{provider_asset_ref:string;sha256:string|null}>).map(a=>({providerAssetRef:a.provider_asset_ref,sha256:a.sha256}));const receipts=(this.db.prepare("SELECT receipt_json FROM browser_execution_tickets WHERE job_id=? AND receipt_json IS NOT NULL ORDER BY issued_at").all(jobId) as Array<{receipt_json:string}>).map(x=>hash(x.receipt_json));return {assetHashes:assets,receiptHashes:receipts};}
  private assertRefs(ids:string[],projectId:string){if(!Array.isArray(ids)||new Set(ids).size!==ids.length)throw new Error("REFERENCE_VERSIONS_INVALID");for(const id of ids){this.reference(id);const owner=this.db.prepare("SELECT e.project_id FROM pw_reference_versions r JOIN pw_entities e ON e.id=r.entity_id WHERE r.id=?").get(id) as {project_id:string}|undefined;if(!owner||owner.project_id!==projectId)throw new Error("CROSS_PROJECT_REFERENCE");}}
  private referenceIds(revisionId:string){return (this.db.prepare("SELECT reference_version_id id FROM pw_revision_references WHERE revision_id=? ORDER BY position").all(revisionId) as Array<{id:string}>).map(x=>x.id);}
  private mustProject(id:string){return this.project(id);}; private mustEntity(id:string){return this.entity(id);}
  private project(id:string){const r=this.db.prepare("SELECT * FROM pw_projects WHERE id=?").get(id) as ProjectRow|undefined;if(!r)throw new Error("PROJECT_NOT_FOUND");return project(r);}
  private entity(id:string){const r=this.db.prepare("SELECT * FROM pw_entities WHERE id=?").get(id) as EntityRow|undefined;if(!r)throw new Error("ENTITY_NOT_FOUND");return entity(r);}
  private reference(id:string){const r=this.db.prepare("SELECT * FROM pw_reference_versions WHERE id=?").get(id) as RefRow|undefined;if(!r)throw new Error("REFERENCE_NOT_FOUND");return ref(r);}
  private scene(id:string){const r=this.db.prepare("SELECT * FROM pw_scenes WHERE id=?").get(id) as SceneRow|undefined;if(!r)throw new Error("SCENE_NOT_FOUND");return scene(r);}
  private revision(id:string){const r=this.db.prepare("SELECT * FROM pw_scene_revisions WHERE id=?").get(id) as RevisionRow|undefined;if(!r)throw new Error("REVISION_NOT_FOUND");return revision(r);}
  private currentRevision(sceneId:string){const r=this.db.prepare("SELECT r.* FROM pw_scenes s JOIN pw_scene_revisions r ON r.id=s.current_revision_id WHERE s.id=?").get(sceneId) as RevisionRow|undefined;if(!r)throw new Error("SCENE_REVISION_NOT_FOUND");return revision(r);}
}
type ProjectRow={id:string;name:string;created_at:string};type EntityRow={id:string;project_id:string;display_name:string;kind:string;created_at:string};type RefRow={id:string;entity_id:string;ordinal:number;sha256:string;role:ReferenceRole;source_json:string;created_at:string;superseded_at:string|null};type SceneRow={id:string;project_id:string;ordinal:number;current_revision_id:string;created_at:string};type RevisionRow={id:string;scene_id:string;ordinal:number;prompt:string;model_policy_json:string;invalidated_at:string|null;invalidation_reason:string|null;created_at:string};type CandidateRow={id:string;scene_id:string;revision_id:string;job_id:string;request_hash:string;budget_ledger_id:string;budget_step_key:string;model_policy_json:string;created_at:string;invalidated_at:string|null;invalidation_reason:string|null};type CandidateEvidenceRow={asset_hashes_json:string;receipt_hashes_json:string};
const project=(r:ProjectRow)=>({id:r.id,name:r.name,createdAt:r.created_at});const entity=(r:EntityRow)=>({id:r.id,projectId:r.project_id,displayName:r.display_name,kind:r.kind,createdAt:r.created_at});const ref=(r:RefRow)=>({id:r.id,entityId:r.entity_id,ordinal:r.ordinal,sha256:r.sha256,role:r.role,source:JSON.parse(r.source_json) as ReferenceSource,createdAt:r.created_at,supersededAt:r.superseded_at});const scene=(r:SceneRow)=>({id:r.id,projectId:r.project_id,ordinal:r.ordinal,currentRevisionId:r.current_revision_id,createdAt:r.created_at});const revision=(r:RevisionRow)=>({id:r.id,sceneId:r.scene_id,ordinal:r.ordinal,prompt:r.prompt,modelPolicy:JSON.parse(r.model_policy_json) as ModelPolicy,invalidatedAt:r.invalidated_at,invalidationReason:r.invalidation_reason,createdAt:r.created_at});
